service: pagaleve-customer-service

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    DYNAMODB_USERS_TABLE: users
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource:
            - "arn:aws:dynamodb:us-east-1:*:table/${self:provider.environment.DYNAMODB_USERS_TABLE}"

plugins:
  - serverless-offline

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post

  findUser:
    handler: handler.findUser
    events:
      - http:
          path: users/{userId}
          method: get

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{userId}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{userId}
          method: delete

  listUsers:
    handler: handler.listUsers
    events:
      - http:
          path: users
          method: get

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
