service: pagaleve-customer-service

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
